spring:
  application:
    name: nasrin-micro-io
  cloud:
    kubernetes:
      config:
        enabled: true
        name: nasrin-micro-io
        namespace: default
      reload:
        enabled: true
    stream:
      kafka:
        binder:
          autoCreateTopics: true
          replication-factor: 1
      bindings:
        event-in:
          destination: events-topic
          contentType: application/json
        event-out:
          destination: events-topic
          contentType: application/json
logging:
  level:
    root: INFO